import useTitle from "hook/useTitle"

export default function Faqf() {
	useTitle('FAQ');
  return (
    <section className="bg-gray-100 dark:bg-gray-800 dark:text-gray-100">
	<div className="container flex flex-col justify-center px-5 md:px-20 lg:px-10 pt-20 md:pt-28 lg:pt-28 pb-20 mx-auto">
		<h2 className="font-semibold text-2xl md:text-3xl lg:text-3xl">Frequently Asked Questions</h2>
        <div className="divider my-1 bg-primary h-[5px] w-[5%] "></div>
		<p className="mt-2 mb-8 dark:text-gray-400 lg:w-[60%]">We can enhance user satisfaction, reduce support inquiries, and provide a convenient resource for users to find the information they need quickly and easily.</p>
		<div className="space-y-4">
			<details className="w-full border rounded-lg" open="">
				<summary className="px-4 py-6 font-semibold focus:outline-none focus-visible:ri">What is a real estate AI product?</summary>
				<p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">A real estate AI product is a software application that utilizes artificial intelligence technology to
                enhance various aspects of the real estate industry, such as property valuation, market analysis,property management, and customer service.</p>
			</details>
			<details className="w-full border rounded-lg">
				<summary className="px-4 py-6 font-semibold focus:outline-none focus-visible:ri">How does a real estate AI product determine property values?</summary>
				<p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">A real estate AI product determines property values by analyzing a wide range of data, including property characteristics, location, recent sales data, market trends, and comparable properties. It uses machine learning algorithms to generate accurate and data-driven property valuations.</p>
			</details>
			<details className="w-full border rounded-lg">
				<summary className="px-4 py-6 font-semibold focus:outline-none focus-visible:ri">Can a real estate AI product predict future property market trends?</summary>
				<p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Yes, a real estate AI product can predict future property market trends by analyzing historical data,
                market indicators, economic factors, and other relevant information. It uses predictive analytics algorithms to provide insights and forecasts regarding property price changes, supply and demand, and investment opportunities. </p>
			</details>
			<details className="w-full border rounded-lg">
				<summary className="px-4 py-6 font-semibold focus:outline-none focus-visible:ri">How can a real estate AI product assist property buyers?</summary>
				<p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">A real estate AI product can assist property buyers by providing personalized property recommendations based on their preferences and requirements. It can also help with property searches, virtual property tours, mortgage pre-approval, and answering inquiries through chatbot interfaces.</p>
			</details>
			<details className="w-full border rounded-lg">
				<summary className="px-4 py-6 font-semibold focus:outline-none focus-visible:ri"> What are the benefits of using a real estate AI product for property sellers?</summary>
				<p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Using a real estate AI product can benefit property sellers in various ways. It can provide accurate
                property valuations, suggest optimal listing prices, create compelling property descriptions, and identify potential buyers through data analysis. It can also help with marketing strategies and automate tasks such as scheduling property showings.</p>
			</details>
			<details className="w-full border rounded-lg">
				<summary className="px-4 py-6 font-semibold focus:outline-none focus-visible:ri">Does a real estate AI product replace the need for real estate agents?</summary>
				<p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">No, a real estate AI product does not replace the need for real estate agents. Instead, it complements
                their expertise by providing valuable data-driven insights and automating certain tasks. Real estate agents play a crucial role in negotiations, building relationships, and offering personalized advice and support to clients.</p>
			</details>
			<details className="w-full border rounded-lg">
				<summary className="px-4 py-6 font-semibold focus:outline-none focus-visible:ri">How accurate are the property valuations generated by a real estate AI product?</summary>
				<p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">The accuracy of property valuations generated by a real estate AI product depends on the quality and
                availability of data, as well as the sophistication of the AI algorithms used. Reputable AI products strive for high accuracy by continuously improving their algorithms and validating results against real-world data.</p>
			</details>
		</div>
	</div>
</section>
  )
}
